algo=(input('digite algo'))
print('tipo: ',type(algo))
print('é numerico ',algo.isnumeric())
print('é alfabetico: ',algo.isalpha())
print('é alfanumerico: ',algo.isalnum())
print('so tem espaço: ',algo.isspace())
print('é maisculo: ',algo.isupper())
print('é minusculo :', algo.islower())
print('esta capitalizada: ',algo.istitle())